/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FindTime API
 * 겹치는 시간 찾기 API
 * OpenAPI spec version: 1.0
 */

export interface CreateRoomDto {
  name?: string;
  creatorId: string;
  /** 방 생성자 닉네임 */
  creatorName: string;
  /** 방 생성자 썸네일 ID */
  creatorThumbnail?: string;
  /** 대상 날짜 리스트 (YYYY-MM-DD) */
  dates: string[];
  /** 시작 시각 (HH:mm) */
  startTime: string;
  /** 종료 시각 (HH:mm) */
  endTime: string;
}
