/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FindTime API
 * 겹치는 시간 찾기 API
 * OpenAPI spec version: 1.0
 */
import type { ParticipantDto } from './participantDto';
import type { RoomDto } from './roomDto';

export interface RoomDetailDataDto {
  room: RoomDto;
  participants: ParticipantDto[];
}
