/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FindTime API
 * 겹치는 시간 찾기 API
 * OpenAPI spec version: 1.0
 */

export interface SlotDto {
  /** 날짜 (YYYY-MM-DD) */
  date: string;
  /** 슬롯 시작 시각 (HH:mm, 00분 또는 30분) */
  time: string;
}
