/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FindTime API
 * 겹치는 시간 찾기 API
 * OpenAPI spec version: 1.0
 */

export interface UpdateNicknameDto {
  /** 유저 ID */
  userId: string;
  /** 변경할 닉네임 */
  name: string;
}
