/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FindTime API
 * 언제만나 API
 * OpenAPI spec version: 1.0
 */

export interface AvailabilitySlotDto {
  /** 날짜 (YYYY-MM-DD) */
  date: string;
  /** 슬롯 시작 시각 (HH:mm, 00분 또는 30분) */
  time: string;
}
