/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FindTime API
 * 언제만나 API
 * OpenAPI spec version: 1.0
 */

export interface RoomDto {
  id: string;
  name?: string;
  creatorId: string;
  dates: string[];
  startTime: string;
  endTime: string;
  createdAt: string;
  expiresAt: string;
}
