/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FindTime API
 * 언제만나 API
 * OpenAPI spec version: 1.0
 */
import type { AvailabilitySlotDto } from './availabilitySlotDto';

export interface SubmitAvailabilityDto {
  /** 프론트에서 생성한 UUID */
  participantId: string;
  participantName: string;
  participantThumbnail?: string;
  slots: AvailabilitySlotDto[];
}
