/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * FindTime API
 * 언제만나 API
 * OpenAPI spec version: 1.0
 */

export interface UpdateRoomNameDto {
  /** 방 생성자 ID */
  creatorId: string;
  /** 변경할 방 이름 */
  name: string;
}
